#version : '3'
version : '3.4'
services:
  calculix-adapter: 
    image: "${SYSTEST_REMOTE}calculix-adapter${PRECICE_BASE}:${CALCULIX_TAG}"
    networks: 
      - precicecomm
    volumes:
      - exchange:/home/precice/Data/Exchange/
      - output:/home/precice/Data/Output/
      - input_solid:/home/precice/Data/Input/
      - configs:/home/precice/calculix-adapter/configs
    command: >
            /bin/bash -c "ln -sf /home/precice/Data/Input Solid; 
            ln -sf /home/precice/calculix-adapter/configs/* . &&
            ccx_preCICE -i Solid/flap -precice-participant Calculix &&
            cp   Solid/*.dat  Solid/*.cvg Solid/*.sta *.log *.out /home/precice/Data/Output/"
    container_name: calculix-adapter
    depends_on:
    - tutorial-data

  su2-adapter:
    image: "${SYSTEST_REMOTE}su2-adapter${PRECICE_BASE}:${SU2_TAG}"
    networks: 
      - precicecomm
    volumes:
      - exchange:/home/precice/Data/Exchange/
      - output:/home/precice/Data/Output/
      - input_fluid:/home/precice/Data/Input/
      - configs:/home/precice/su2-adapter/configs
    command: >  
              /bin/bash -c "ln -sf /home/precice/Data/Input Fluid && 
                ln -sf /home/precice/su2-adapter/configs/* . &&
                SU2_CFD Fluid/euler_config_coupled.cfg &&
                cp *.vtk *.csv *.dat *SU2*.log /home/precice/Data/Output/"
    container_name: su2-adapter
    depends_on: 
    - tutorial-data

  tutorial-data:
    build:
      network: host
      context: .
      dockerfile: Dockerfile.tutorial_data
    volumes:
      - input_solid:/tutorials/FSI/flap_perp/SU2-CalculiX/Solid
      - input_fluid:/tutorials/FSI/flap_perp/SU2-CalculiX/Fluid
      - configs:/configs/
      - output:/Output/
    container_name: tutorial-data 

networks:
  precicecomm:
volumes:
  exchange:
  output:
  configs:
  input_solid:
  input_fluid:
