# for network
version : '3.4'
#version : '3'
services:
  
  dealii-adapter: 
    image: "${SYSTEST_REMOTE}dealii-adapter${PRECICE_BASE}:${DEALII_TAG}"
    networks: 
      - precicecomm
    volumes:
      - exchange:/home/precice/Data/Exchange/
      - input_dealii:/home/precice/Data/Input/
      - configs:/home/precice/dealii-adapter/configs/
      - output:/home/precice/Data/Output/
    command: >
      /bin/bash -c "
      ln -sf configs/* . && 
      ./coupled_elasto_dynamics /home/precice/Data/Input/parameters.prm"
    container_name: dealii-adapter
    depends_on:
      - tutorial-data
      - openfoam-adapter
    
  openfoam-adapter: 
    image: "${SYSTEST_REMOTE}openfoam-adapter${PRECICE_BASE}:${OPENFOAM_TAG}"
    networks: 
      - precicecomm
    volumes:
      - exchange:/home/precice/Data/Exchange/
      - input_of:/home/precice/Data/Input/
      - configs:/home/precice/openfoam-adapter/configs/
      - output:/home/precice/Data/Output/
    command: >
      /bin/bash -c "source /opt/openfoam4/etc/bashrc && 
      ln -sf configs/* . &&
      blockMesh -case /home/precice/Data/Input &&
      checkMesh -case /home/precice/Data/Input &&
      pimpleDyMFoam -case /home/precice/Data/Input &&
      cp -r /home/precice/Data/Input/. /home/precice/Data/Output/Fluid"
    container_name: openfoam-adapter
    depends_on:
      - tutorial-data

  tutorial-data:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.tutorial_data
    volumes:
      - input_of:/tutorials/FSI/flap_perp/OpenFOAM-deal.II/Fluid
      - input_dealii:/tutorials/FSI/flap_perp/OpenFOAM-deal.II/Solid
      - configs:/configs/
      - output:/Output/
    container_name: tutorial-data

networks:
  precicecomm:
volumes:
  exchange:
  input_dealii:
  input_of:
  output:
  configs:
